services:

  db:
    image: mysql:9.2

    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ../mysql/sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: "bash -c \"mysql --user=$$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD --execute \\\"SELECT COUNT(*) FROM ynov_ci.utilisateurs HAVING COUNT(*) = 4;\\\" || exit 1\""
      interval: 5s
      timeout: 5s
      retries: 4

  mongo:
    build:
      context: ../mongo
      dockerfile: Dockerfile 
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - ../mongo:/docker-entrypoint-initdb.d/
      - mongo_data:/data/db
    healthcheck:
      test: "mongosh --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --eval \"const count = db.getSiblingDB('blog_db').posts.countDocuments(); if (count !== 5) { quit(1); }\" || exit 1"
      interval: 5s
      timeout: 5s
      retries: 4

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH=${ME_CONFIG_BASICAUTH}
    depends_on:
      mongo:
        condition: service_healthy

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  server:
    build:
      context: ../python
      dockerfile: Dockerfile 
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ../python:/python
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_ROOT_USER=${MONGO_ROOT_USER}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy

    command: ["uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]

    healthcheck:
      test: "curl -sf http://localhost:8000/posts && curl -sf http://localhost:8000/users || exit 1"
      interval: 5s
      timeout: 5s
      retries: 4
      start_period: 2s

volumes:
  mysql_data:
  mongo_data: